### PR TITLE
amgrss update to add amg:coverageRestrictions

### PR DESCRIPTION
**Pull request by shashi-banger**
PR for issue #64

### CODE REVIEW

**Review by vsagarv — CHANGES_REQUESTED** [review]
@shashi-banger xpaths for publicationRestrictions are missing.

**Comment by shashi-banger** [comment]
@vsagarv added xpaths for publicationRestrictions also

**Review by allwindsouza — APPROVED** [review]
LGTM

**Comment by vsagarv** [comment]
Checked publicationRestrictions xpaths.
LGTM.

**Review by vsagarv — APPROVED** [review]

**Pull request merged**
